### ISSUE TITLE
Govee Errors in EISY Administrative Consule and UD Moble App

### ISSUE THREAD

**Issue by KOLN1011** [UniversalDevicesInc-PG3/udi-govee-nodeserver#3]
EISY is giving me an error when I turn a node on or off in the administrative console:

TCP client request failed [ISY:401]

UD Mobile is giving me a similar error when I turn a device on or off:

xml version="1.0" encoding="UTF-8" RestResponse succeeded="false" status 404  status reason code="1"  RestResponse 

I would appreciate any help you could provide to resolve this issue and hope you are having a wonderful day.

**Comment by bpaauwe** [comment]
A 401 error is an authentication error.  Which indicates that the node server is not properly installed on the IoX/ISY.  You could try re-installing the node server.

A 404 error is a not found error.   This would happen if the node in the IoX/ISY doesn't have a matching node in PG3.  which may also be because the node server isn't properly installed or the node in the IoX/ISY is no longer valid.

**Comment by KOLN1011** [comment]
Bob,

It's a pleasure to meet you. The first time installing the Govee node server was super easy, and after selecting the "Add All Nodes" menu item on the EISY Administrative Console, all of my devices showed up. However, selecting on and off would give me the errors I previously stated.

Per your request, I uninstalled and reinstalled the Govee node server and followed the same procedure, however, nothing is being added like it originally did. I did this process three times with the same result and even rebooted my EISY a couple of times. I am new to Polyglot so I am not sure what I am doing wrong. Please advise.

Thank you,
Collin

**Comment by bpaauwe** [comment]
I don't really know anything about the Govee node server.  I didn't write it.  However, i don't believe you should be using the admin console add all nodes menu to add nodes.  I'm surprised that it did anything.

After looking over the source, my understanding is that you have to create a custom parameter called "api_key" and set that to an API key that you get from the Govee app.  Once you do that, the node server will query for lights you've configured in the app and create nodes for those.

Whatever nodes got created when you did the Add All Nodes are probably not valid.

**Comment by KOLN1011** [comment]
Yes, I set up the api_key each time I installed the Govee node server but none of my devices populated except for the first time last Tuesday. All three times I did it again today, nothing transpired. Originally, I had the exact amount of nodes in the EISY as I have in the Govee app and some of them had settings for colors for my led lights while others were just on and off since I have mini smart plugs. So there was a parallel between EISY nodes showing and Govee app devices but none of them would work. Do you think none of my devices are supported? I did buy them all within the past year and a half. Thank you so much for looking into this for me!

**Comment by KOLN1011** [comment]
![image](https://github.com/UniversalDevicesInc-PG3/udi-govee-nodeserver/assets/141965345/6362dd73-06ca-4057-be8c-3b182098868b)

Here is an image of the node that does show up, which I think just shows that everything is linked to my account. Hope this helps.

**Comment by bpaauwe** [comment]
I have no real idea, as I said, I didn't write the node server and have never used it.  I believe the original author has abandoned it.

The best way to go about debugging is to set the node server log level to debug, restart the node server and see what the log shows. It may provide clues as to what is happening (or not happening).   

If the log doesn't mean anything to you, download the log package and attach it here and I'll take a quick look.

**Comment by therealmysteryman** [comment]
I initially created for H6104 led strip and didn’t have any other Govee to test. I only exposed the On Off. 

Unless someone want to take over the nodeserver, I don’t think is very useful a this stage.

**Comment by KOLN1011** [comment]
Thank you for your help, Bob, and thank you for the update, AutomationGeek. Unfortunately, at this juncture, I don't have the time or resources to take over this node server as much as I would like to. Cheers to you both and have a great rest of your weekend!
